import "server-only";
import openapiExamples from "../../source-docs/openapi/examples.json";
import type { EndpointExample } from "./types";

/**
 * Named official request examples per endpoint. The only source is
 * source-docs/openapi/examples.json (generated by
 * scripts/openapi-examples.mjs from the official page snapshots). Kept out
 * of `Endpoint` so the client-side sidebar, which imports the content
 * registry, does not ship ~325 examples in its bundle; read it on the
 * server (Reference pages, and later the Playground).
 */
interface ExampleRow extends EndpointExample {
  operationId: string;
  method: string;
}

const byEndpoint = new Map<string, EndpointExample[]>();
for (const row of openapiExamples.examples as unknown as ExampleRow[]) {
  // Examples made with a global (administrative) key are not customer
  // content (Phase 8E, docs/phases/08E-customer-change-brief.md).
  if (row.keyKind === "global") continue;
  const key = `openapi/${row.operationId}`;
  const list = byEndpoint.get(key) ?? [];
  list.push({
    title: row.title,
    description: row.description,
    path: row.path,
    query: row.query,
    ...(row.body !== undefined ? { body: row.body } : {}),
    keyKind: row.keyKind,
    source: row.source,
  });
  byEndpoint.set(key, list);
}

export function getEndpointExamples(apiId: string, endpointId: string): EndpointExample[] {
  return byEndpoint.get(`${apiId}/${endpointId}`) ?? [];
}
