/**
 * Phase 7 rollout tracker (docs/phases/07-proxy-api-rollout.md "Track").
 * Derives every count from the two sources of truth — the operation
 * inventory (source-docs/proxy-api/operations.json) and the content model
 * (src/content) — and writes source-docs/ROLLOUT_STATUS.md.
 *
 * Also writes source-docs/OPENAPI_DEMO_STATUS.md (Phase 8B §12): the
 * OpenAPI Demo coverage report, one line per operation, from
 * source-docs/openapi/operations.json and the same content model, and
 * source-docs/OPENAPI_PLAYGROUND_STATUS.md (Phase 8C §13): Playground,
 * Demo and Live coverage. The latter imports the real (server-only) Live
 * allowlist, so the script runs with `--conditions=react-server`.
 *
 *   npm run rollout:status
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getApi, listEndpoints } from "../src/content";
import { getDemoFixtures, isDemoSimulatedWrite } from "../src/content/demo";
import { listLiveTargetIds } from "../src/server/playground/allowlist";

interface OperationRow {
  id: string;
  reqtype: string;
  category: string;
  class: "read" | "write" | "unclear";
  keyScope: "admin" | "not_documented";
  source: string;
  excluded?: string;
}

const root = resolve(__dirname, "..");
const srcDir = resolve(root, "source-docs/proxy-api");
const rows = (JSON.parse(readFileSync(resolve(srcDir, "operations.json"), "utf8")) as { operations: OperationRow[] }).operations;
const endpoints = listEndpoints(getApi("proxy")!);
const byId = new Map(endpoints.map((e) => [e.id, e]));

const active = rows.filter((r) => !r.excluded);
const pages = readdirSync(srcDir).filter((f) => f.endsWith(".md") && f !== "README.md");
const count = (pred: (r: OperationRow) => boolean) => active.filter(pred).length;
const ep = (r: OperationRow) => byId.get(r.id);

// Broken links: inventory source files, endpoint `related` ids.
const broken: string[] = [];
for (const r of rows) {
  const file = r.source.split(/[;\s]/)[0];
  if (!existsSync(resolve(srcDir, file))) broken.push(`${r.id}: source ${file}`);
}
for (const e of endpoints) {
  for (const rel of e.related) if (!byId.has(rel)) broken.push(`${e.id}: related ${rel}`);
}

// Open questions and recorded source conflicts.
const unresolved = readFileSync(resolve(root, "source-docs/unresolved.md"), "utf8");
const openItems = [...unresolved.matchAll(/^## (U-\d+)[\s\S]*?- Final status: ([^\n]*)/gm)]
  .filter((m) => !/^\*\*(decided|closed)/.test(m[2]) || /\bopen\b/.test(m[2]))
  .map((m) => `${m[1]} (${m[2].trim()})`);
const conflicts = pages.reduce((n, f) => n + (readFileSync(resolve(srcDir, f), "utf8").match(/UNRESOLVED/g)?.length ?? 0), 0);

const missing = active.filter((r) => !ep(r)).map((r) => r.id);
const lines = [
  "# Proxy API rollout status",
  "",
  "Generated by `npm run rollout:status` from `source-docs/proxy-api/operations.json` and `src/content`. Do not edit by hand.",
  "",
  "## Counts",
  "",
  `- Source pages discovered: ${pages.length} (\`source-docs/proxy-api/*.md\`)`,
  `- Operations discovered: ${rows.length} (${rows.length - active.length} excluded)`,
  `  - read: ${count((r) => r.class === "read")}, write: ${count((r) => r.class === "write")}, unclear: ${count((r) => r.class === "unclear")}`,
  `  - admin key stated: ${count((r) => r.keyScope === "admin")}`,
  `- Endpoints documented (Reference page): ${count((r) => !!ep(r))} / ${active.length}`,
  `- Endpoints tested (real API): ${count((r) => !!ep(r)?.verification.tested)}`,
  `- Endpoints verified: ${count((r) => !!ep(r)?.verification.verified)}`,
  `- Demo fixtures: ${count((r) => !!ep(r) && !!getDemoFixtures("proxy", r.id))}`,
  `- Broken links: ${broken.length}`,
  `- Unresolved questions open: ${openItems.length}`,
  `- Source conflicts marked UNRESOLVED in source-docs/proxy-api: ${conflicts}`,
  "",
  "## Operations without a Reference page",
  "",
  ...(missing.length ? missing.map((id) => `- ${id}`) : ["None."]),
  "",
  "## Excluded operations",
  "",
  ...rows.filter((r) => r.excluded).map((r) => `- ${r.id}: ${r.excluded}`),
  "",
  "## Open unresolved items",
  "",
  ...(openItems.length ? openItems.map((i) => `- ${i}`) : ["None."]),
  "",
  "## Broken links",
  "",
  ...(broken.length ? broken.map((b) => `- ${b}`) : ["None."]),
  "",
];

writeFileSync(resolve(root, "source-docs/ROLLOUT_STATUS.md"), lines.join("\n"));
console.log(lines.slice(4, 18).join("\n"));

// --- OpenAPI Demo coverage (Phase 8B §12) ---

interface OpenapiOperationRow {
  id: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  operationClass: "read" | "write";
  file: string;
  page: string;
  securityReview: string;
}

const oaSrcDir = resolve(root, "source-docs/openapi");
const oaRows = (JSON.parse(readFileSync(resolve(oaSrcDir, "operations.json"), "utf8")) as { operations: OpenapiOperationRow[] })
  .operations;
const oaEndpoints = listEndpoints(getApi("openapi")!);
const oaById = new Map(oaEndpoints.map((e) => [e.id, e]));

const probeFile = JSON.parse(
  readFileSync(resolve(root, "source-docs/observed/openapi/probe-2026-09-26.masked.json"), "utf8"),
) as { probe: Record<string, { status?: number }>; followup: Record<string, { status?: number }> };
const probedStatus = new Map<string, number | undefined>();
for (const [k, v] of Object.entries(probeFile.probe)) probedStatus.set(k.split(" (")[0], v.status);
for (const [k, v] of Object.entries(probeFile.followup)) {
  const base = k.split(" (")[0];
  if (v.status === 200 || !probedStatus.has(base)) probedStatus.set(base, v.status);
}

// Global-key-only resources (SEC-REQ-28 §4): excluded from the probe by
// design, not merely unfixtured — see docs/DECISIONS.md "Phase 8B planning
// and probe decisions".
const GLOBAL_KEY_ONLY = new Set(["providers", "routingprofiles", "tenants", "userprofiles", "users"]);

function oaReason(r: OpenapiOperationRow): string {
  if (r.operationClass === "write") return "write (Reference-only, SEC-REQ-27)";
  if (getDemoFixtures("openapi", r.id)) return "Demo-supported";
  const slug = r.id.replace(/-(list|get)(-.*)?$/, "");
  if (GLOBAL_KEY_ONLY.has(slug)) return "not probed (global-key-only resource)";
  if (r.id === "cdrs-list") return "not probed (docs: may repair CDR metadata; a possible side effect)";
  const status = probedStatus.get(r.id);
  if (status === undefined) return "not probed";
  if (status !== 200) return `probed — HTTP ${status}, no fixturable success data`;
  return "probed — no fixturable data (empty result or timeout)";
}

const oaWrites = oaRows.filter((r) => r.operationClass === "write");
const oaReads = oaRows.filter((r) => r.operationClass === "read");
const oaSupported = oaReads.filter((r) => getDemoFixtures("openapi", r.id));
const oaMissingPage = oaRows.filter((r) => !oaById.has(r.id)).map((r) => r.id);

const oaLines = [
  "# OpenAPI Demo coverage status",
  "",
  "Generated by `npm run rollout:status` from `source-docs/openapi/operations.json`, `src/content` and the Phase 8B masked probe (`source-docs/observed/openapi/probe-2026-09-26.masked.json`). Do not edit by hand.",
  "",
  "## Counts",
  "",
  `- Total OpenAPI operations: ${oaRows.length}`,
  `- Reference pages: ${oaRows.length - oaMissingPage.length} / ${oaRows.length}`,
  `- Write operations (Reference-only, never Demo-supported): ${oaWrites.length}`,
  `- Read operations: ${oaReads.length}`,
  `  - Demo-supported: ${oaSupported.length}`,
  `  - Not Demo-supported: ${oaReads.length - oaSupported.length}`,
  "",
  "## Read operations without a fixture, and why",
  "",
  ...oaReads
    .filter((r) => !getDemoFixtures("openapi", r.id))
    .map((r) => `- ${r.id}: ${oaReason(r)}`),
  "",
  "## Operations without a Reference page",
  "",
  ...(oaMissingPage.length ? oaMissingPage.map((id) => `- ${id}`) : ["None."]),
  "",
];

writeFileSync(resolve(root, "source-docs/OPENAPI_DEMO_STATUS.md"), oaLines.join("\n"));
console.log("\n" + oaLines.slice(4, 12).join("\n"));

// --- OpenAPI Playground coverage (Phase 8C §13) ---

const oaCategories = getApi("openapi")!.categories;
const sourceOf = (r: OpenapiOperationRow) => r.file.replace("source-docs/openapi/", "").replace(/\.md$/, "");
const oaResources = [...new Set(oaRows.map(sourceOf))].sort();
// A resource is represented when every one of its operations resolves to an endpoint the picker lists.
const oaRepresentedResources = oaResources.filter((res) =>
  oaRows.filter((r) => sourceOf(r) === res).every((r) => oaById.has(r.id)),
);
// Categories that hold more than one official page, so pages and categories reconcile.
const oaSharedCategories = oaCategories
  .map((c) => {
    const pages = [...new Set(oaRows.filter((r) => oaById.get(r.id)?.category === c.id).map(sourceOf))];
    return pages.length > 1 ? `${c.id} holds ${pages.join(" + ")}` : null;
  })
  .filter((x): x is string => x !== null);
const oaRepresentedOps = oaRows.filter((r) => oaById.has(r.id));
const oaLive = listLiveTargetIds().filter((id) => id.startsWith("openapi/"));
const oaWritesSimulatable = oaWrites.filter((r) => isDemoSimulatedWrite("openapi", { id: r.id, operationClass: "write" }));
const oaWritesWithResponse = oaWrites.filter((r) => (oaById.get(r.id)?.responses.length ?? 0) > 0);
const oaReadsNoDemo = oaReads.filter((r) => !getDemoFixtures("openapi", r.id));
const oaDemoExecutable = oaSupported.length + oaWritesSimulatable.length;

// Operations used as the §14 representative checks (each must exist).
const REPRESENTATIVE: [string, string][] = [
  ["extensions-list", "read-only GET"],
  ["extensions-get", "parameterized GET (path ID)"],
  ["campaigns-create", "CRUD-style resource, write (string, integer and array body fields)"],
  ["extensions-create", "mutating operation that must stay Live-disabled (secret-named body field)"],
  ["cdrs-list", "operation with no documented or observed response schema in Demo"],
  ["tenants-list", "global/admin-scoped resource (global API key)"],
];
const oaMissingRepresentative = REPRESENTATIVE.filter(([id]) => !oaById.has(id)).map(([id]) => id);

const pgLines = [
  "# OpenAPI Playground coverage status",
  "",
  "Generated by `npm run rollout:status` from `source-docs/openapi/operations.json`, `src/content` (including the Demo fixture registry) and the real Live allowlist (`src/server/playground/allowlist.ts`). Do not edit by hand. Phase 8C §13.",
  "",
  "## Representation",
  "",
  `- Documented resources (distinct official pages in the inventory): ${oaResources.length}`,
  `- Resources represented in the Playground: ${oaRepresentedResources.length} / ${oaResources.length}`,
  `- Picker categories: ${oaCategories.length}${oaSharedCategories.length ? ` (${oaSharedCategories.join("; ")})` : ""}`,
  `- Documented operations: ${oaRows.length}`,
  `- Operations represented in the Playground: ${oaRepresentedOps.length} / ${oaRows.length}`,
  "",
  "## Execution",
  "",
  `- Executable in Demo: ${oaDemoExecutable}`,
  `  - Reads with a fixture set: ${oaSupported.length} / ${oaReads.length}`,
  `  - Writes simulated from a documented example: ${oaWritesSimulatable.length} / ${oaWrites.length}`,
  `- Executable in Live: ${oaLive.length}${oaLive.length ? ` (${oaLive.join(", ")})` : ""}`,
  `- Visible but intentionally Live-disabled: ${oaRows.length - oaLive.length}`,
  `- Visible, request preview only (Send blocked in Demo): ${oaRows.length - oaDemoExecutable}`,
  `  - Reads with no fixture: ${oaReadsNoDemo.length}`,
  `  - Writes: ${oaWrites.length - oaWritesSimulatable.length}`,
  "",
  "## Writes and documented responses",
  "",
  `${oaWritesWithResponse.length} of ${oaWrites.length} writes document a success response (${oaWritesWithResponse.map((r) => r.id).join(", ") || "none"}). Simulating a write needs a documented example; the documented ones are excluded from Demo by SEC-REQ-05 (Auth Token) and SEC-REQ-06 (Dial). Simulatable writes: ${oaWritesSimulatable.length}.`,
  "",
  "## Missing operations",
  "",
  ...(oaRows.length - oaRepresentedOps.length ? oaRows.filter((r) => !oaById.has(r.id)).map((r) => `- ${r.id}`) : ["None."]),
  "",
  "## Intentionally excluded operations",
  "",
  "None are hidden from the Playground. Operations that cannot be sent, and why:",
  "",
  `- All ${oaRows.length}: Live is default-deny (no OpenAPI id on the Live allowlist; SEC-REQ-27/28).`,
  `- ${oaWrites.length} writes: never sent in Live; Demo only from a documented example (SEC-REQ-27, amended 2026-10-01).`,
  ...oaReadsNoDemo.map((r) => `- ${r.id}: no Demo data — ${oaReason(r)}`),
  "",
  "## Resources",
  "",
  ...oaResources.map((res) => {
    const rows = oaRows.filter((r) => sourceOf(r) === res);
    const cats = [...new Set(rows.map((r) => oaById.get(r.id)?.category).filter(Boolean))];
    return `- ${res}: ${rows.length} operation${rows.length === 1 ? "" : "s"}, ${rows.filter((r) => getDemoFixtures("openapi", r.id)).length} with Demo data, category ${cats.join(" / ") || "—"}`;
  }),
  "",
  "## Representative checks (§14)",
  "",
  ...REPRESENTATIVE.map(([id, why]) => `- ${id}: ${why}${oaById.has(id) ? "" : " — MISSING"}`),
  ...(oaMissingRepresentative.length ? ["", `Missing representative operations: ${oaMissingRepresentative.join(", ")}`] : []),
  "",
];

writeFileSync(resolve(root, "source-docs/OPENAPI_PLAYGROUND_STATUS.md"), pgLines.join("\n"));
console.log("\n" + pgLines.slice(4, 24).join("\n"));
