/**
 * Phase 7 rollout tracker (docs/phases/07-proxy-api-rollout.md "Track").
 * Derives every count from the two sources of truth — the operation
 * inventory (source-docs/proxy-api/operations.json) and the content model
 * (src/content) — and writes source-docs/ROLLOUT_STATUS.md.
 *
 *   npm run rollout:status
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getApi, listEndpoints } from "../src/content";
import { getDemoFixtures } from "../src/content/demo";

interface OperationRow {
  id: string;
  reqtype: string;
  category: string;
  class: "read" | "write" | "unclear";
  keyScope: "admin" | "not_documented";
  source: string;
  excluded?: string;
}

const root = resolve(__dirname, "..");
const srcDir = resolve(root, "source-docs/proxy-api");
const rows = (JSON.parse(readFileSync(resolve(srcDir, "operations.json"), "utf8")) as { operations: OperationRow[] }).operations;
const endpoints = listEndpoints(getApi("proxy")!);
const byId = new Map(endpoints.map((e) => [e.id, e]));

const active = rows.filter((r) => !r.excluded);
const pages = readdirSync(srcDir).filter((f) => f.endsWith(".md") && f !== "README.md");
const count = (pred: (r: OperationRow) => boolean) => active.filter(pred).length;
const ep = (r: OperationRow) => byId.get(r.id);

// Broken links: inventory source files, endpoint `related` ids.
const broken: string[] = [];
for (const r of rows) {
  const file = r.source.split(/[;\s]/)[0];
  if (!existsSync(resolve(srcDir, file))) broken.push(`${r.id}: source ${file}`);
}
for (const e of endpoints) {
  for (const rel of e.related) if (!byId.has(rel)) broken.push(`${e.id}: related ${rel}`);
}

// Open questions and recorded source conflicts.
const unresolved = readFileSync(resolve(root, "source-docs/unresolved.md"), "utf8");
const openItems = [...unresolved.matchAll(/^## (U-\d+)[\s\S]*?- Final status: ([^\n]*)/gm)]
  .filter((m) => !/^\*\*(decided|closed)/.test(m[2]) || /\bopen\b/.test(m[2]))
  .map((m) => `${m[1]} (${m[2].trim()})`);
const conflicts = pages.reduce((n, f) => n + (readFileSync(resolve(srcDir, f), "utf8").match(/UNRESOLVED/g)?.length ?? 0), 0);

const missing = active.filter((r) => !ep(r)).map((r) => r.id);
const lines = [
  "# Proxy API rollout status",
  "",
  "Generated by `npm run rollout:status` from `source-docs/proxy-api/operations.json` and `src/content`. Do not edit by hand.",
  "",
  "## Counts",
  "",
  `- Source pages discovered: ${pages.length} (\`source-docs/proxy-api/*.md\`)`,
  `- Operations discovered: ${rows.length} (${rows.length - active.length} excluded)`,
  `  - read: ${count((r) => r.class === "read")}, write: ${count((r) => r.class === "write")}, unclear: ${count((r) => r.class === "unclear")}`,
  `  - admin key stated: ${count((r) => r.keyScope === "admin")}`,
  `- Endpoints documented (Reference page): ${count((r) => !!ep(r))} / ${active.length}`,
  `- Endpoints tested (real API): ${count((r) => !!ep(r)?.verification.tested)}`,
  `- Endpoints verified: ${count((r) => !!ep(r)?.verification.verified)}`,
  `- Demo fixtures: ${count((r) => !!ep(r) && !!getDemoFixtures("proxy", r.id))}`,
  `- Broken links: ${broken.length}`,
  `- Unresolved questions open: ${openItems.length}`,
  `- Source conflicts marked UNRESOLVED in source-docs/proxy-api: ${conflicts}`,
  "",
  "## Operations without a Reference page",
  "",
  ...(missing.length ? missing.map((id) => `- ${id}`) : ["None."]),
  "",
  "## Excluded operations",
  "",
  ...rows.filter((r) => r.excluded).map((r) => `- ${r.id}: ${r.excluded}`),
  "",
  "## Open unresolved items",
  "",
  ...(openItems.length ? openItems.map((i) => `- ${i}`) : ["None."]),
  "",
  "## Broken links",
  "",
  ...(broken.length ? broken.map((b) => `- ${b}`) : ["None."]),
  "",
];

writeFileSync(resolve(root, "source-docs/ROLLOUT_STATUS.md"), lines.join("\n"));
console.log(lines.slice(4, 18).join("\n"));
